my_portfolio_website/my_contact_data/urls.py
from django.urls import include, path
from my_contact_data import views
 
app_name = 'my_contact_data'
 
urlpatterns = [
     path('', views.home,name='home'),
     path('portfolio', views.portfolio,name='portfolio'),
     path('contactdata', views.contactus,name='contactdata'),
     path('resume', views.resume ,name='resume'),
     path('contact_form_submit',views.contact_form_submit,name='contact_form_submit'),

]

my_portfolio_website/my_portfolio_website/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('my_contact_data.urls')),
]

my_portfolio_website/my_contact_data/models.py
from django.db import models

#Contact Form Model
class ContactForm(models.Model):
    #Total Fields : 5
    #------Contact form Table Fields------

    #This field store Full Name 
    full_name = models.CharField(max_length=300,blank=True)
    #This field store Email ID
    email_id = models.CharField(max_length=300,blank=True)
    #This field store Contact Number 
    contact_number = models.CharField(max_length=300,blank=True)
    #This field store Message 
    message = models.TextField(max_length=3000,blank=True)
    #This field store Date & Time at which form is submitted
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.pk) #Return Primary Key

    class Meta:
        verbose_name_plural = "Contact Form Data"
        verbose_name = "Contact Form"

my_portfolio_website/my_contact_data/views.py
from django.shortcuts import render,HttpResponseRedirect,HttpResponse
from django.urls import reverse
from django.shortcuts import render
from my_contact_data.models import ContactForm

# Create your views here.
def home(request):
    return render(request,'my_contact_data/home.html')

def portfolio(request):
    return render(request,'my_contact_data/portfolio.html')

def contactus(request):
    my_contact_form_data = ContactForm.objects.all()
    data = {'my_contact_form_data': my_contact_form_data}
    return render(request,'my_contact_data/contactdata.html',data)

def resume(request):
    return render(request,'my_contact_data/resume.html')

def contact_form_submit(request):
    """This view take post method and submit form details 
        by creating ContactForm Model object
    parameters: HttpRequest
    return: if form data submit successfully then 
            HttpResponseRedirect to page contact.html  """
    if request.method == "POST":
        full_name = request.POST['full_name']
        email_id = request.POST['email_id']
        contact_number = request.POST['contact_number']
        message = request.POST['message']
        ContactForm.objects.create(full_name=full_name,
                                   email_id=email_id,
                                   contact_number=contact_number,
                                   message=message
                                   )
    return HttpResponseRedirect(reverse('my_contact_data:contactdata'))

my_portfolio_website/my_contact_data/templates/my_contact_data/base.html
<!DOCTYPE html>
<html>
{% load static %}
<head>
    <title>My Portfolio</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel='stylesheet' href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.1.0-4/css/all.css">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    {% block stylesheets %}
    {% endblock stylesheets %}  
    
    {% block headscript %}
    {% endblock headscript %}
    <style>
        body {
            background-color: #E8E8E8;
        }
    </style>
</head>
<body>
    <div>
        <nav class="navbar navbar-expand-lg navbar-dark bg-info fixed-top">
            <a class="navbar-brand"><b>My Portfolio</b></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
                <ul class="navbar-nav ml-auto ">
                    <li class="nav-item ">
                        <a class="nav-link" style="color: #fff" href="{% url 'my_contact_data:home' %}">About</a>
                    </li> 
                    <li class="nav-item ">
                        <a class="nav-link" style="color: #fff" href="{% url 'my_contact_data:resume' %}">Resume</a>
                    </li>
                    <li class="nav-item ">
                        <a class="nav-link" style="color: #fff" href="{% url 'my_contact_data:portfolio' %}">Portfolio </a>
                      </li>
                      <li class="nav-item ">
                          <a class="nav-link" style="color: #fff" href="{% url 'my_contact_data:contactdata' %}">Contact</a>
                      </li>
                  </ul>
              </div>
          </nav>
      </div>
      {% block content %}
      {% endblock %}
      
      {% block script %}
      {% endblock %}
  </body>
  </html>

my_portfolio_website/my_contact_data/templates/my_contact_data/contactdata.html
{% extends 'my_contact_data/base.html' %}
{% load static %}

{% block stylesheets %}
<style>
    .box {
        margin-top: 6rem;

    }

    ul {
        position: relative;
        right: 0;
    }

    .row input {
        margin-bottom: 2rem;
        border: 0;
        box-shadow: 0;!important
    }

    .row textarea {
        margin-bottom: 2rem;
        border: 0;
    }

    .box h1 {
        margin-bottom: 5rem;
    }

    .icons {
        margin-top: 3rem;
    }

    .copy {
        margin-top: 1rem;
    }

    .icons a {
        color: #ccc;
        margin: 1rem;
    }

    .icons a:hover {
        color: #000;
    }
</style>

{% endblock stylesheets %}


{% block headscript %}
{% endblock headscript %}


{% block content %}
<div class="container">

    <div class="box shadow-lg p-3 mb-5 bg-white rounded">
        <div class="">
            <center>
                <h1 style="color: #15aabf">CONTACT ME</h1>
            </center>
        </div>
        <div class=" container">
            <form method="POST" action="{% url 'my_contact_data:contact_form_submit' %}">
                {% csrf_token %}
                <div class="row">
                    <div class="form-group col-sm-4">
                        <input type="text" id="full_name" name="full_name" class="form-control form-control-lg border-bottom border-dark shadow-none" placeholder="Name">
                    </div>
                    <div class="form-group  col-sm-4">
                        <input type="text" id="email_id" name="email_id" class="form-control form-control-lg border-bottom border-dark shadow-none" placeholder="Email">
                    </div>
                    <div class="form-group col-sm-4">
                        <input type="text" id="contact_number" name="contact_number" class="form-control form-control-lg border-bottom border-dark shadow-none" placeholder="Contact">
                    </div>

                </div>
                <div class="row">
                    <div class="col-md-12">
                        <textarea id="message" name="message" class="form-control form-control-lg border-bottom border-dark shadow-none" rows="5" placeholder="Your Message"></textarea>
                    </div>
                    <div class="col-md-12">
                        <center> <button type="submit" class="btn-info btn btn-lg">Submit</button></center>
                    </div>

                </div>
            </form>

        </div>
        <div class="container">
            <div class="icons">
                <center>
                    <a href="#"><span class="fab fa-github fa-2x"></span></a>
                    <a href="#"><i class="fab fa-linkedin fa-2x"></i></a>
                </center>

            </div>
        </div>
        <div class="container">
            <div class="copy">
                <center>
                    <h6>&copy;2020 My Portfolio</h6>
                </center>

            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block script %}
{% endblock %}

my_portfolio_website/my_contact_data/templates/my_contact_data/home.html
{% extends 'my_contact_data/base.html' %}
{% load static %}
{% block stylesheets %}
<style>
        .img-container img {
            border-radius: 50%;
            margin-bottom: 2rem;
        }
        .img-container {
            margin-top: 2rem;
        }
        .personal {
            padding: 3rem;
        }
        .detail {
            padding: 3rem;
        }
        .detail i {
            margin-right: 1rem;
            color: #15aabf;
        }
        b {
            padding-right: 10px;
        }
        .card {
            margin-top: 6rem;
        }
        ul {
            position: relative;
            right: 0;
        }
        .useful_link a {
            color: #ccc;
            margin: 1rem;
        }
        .useful_link a:hover {
            color: #000;
        }
        .profile_name h1,
        h5 {
            margin: 1rem;
        }
    </style>
    {% endblock stylesheets %}

    {% block headscript %}
    {% endblock headscript %}

{% block content %}
    <div class="container">
        <div class="col-sm-12">
            <div class="card shadow-lg p-3 mb-5 bg-white rounded">
                <div class="row ">
                    <div class="img-container mx-auto">
                        <img  src="{% static 'my_contact_data/images/avatar.png' %}">
                    </div>
                </div>
                <div class="row align-self-center">
                    <div class="profile_name text-center">
                        <h1>Siddhant Mishra</h1>
                        <h5>I'm Cross-Paltform Developer</h5>
                        <div class="useful_link ml-auto">
                            <center>
                                <a href="#"><span class="fab fa-github fa-2x"></span></a>
                                <a href="#"><span class="fab fa-linkedin fa-2x"></span></a>
                            </center>
                        </div>
                    </div>
                </div>
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-6 personal">
                            <h3 style="font-weight: bold">Personal Detail</h3>
                            <p>A Cross Platform App Developer. Prefer's Tea over Coffee 😜. I love to play around with technology. Currently pursuing Degree in Computer Engineering. Have a keen interest in programming and playing around with technology. I love development, be it website's or apps and also ui designing.</p>
                        </div>
                        <div class="col-md-6 detail">
                            <p><i class="far fa-user-circle"></i><b>Name:</b> Siddhant </p>
                            <p><i class="fas fa-phone"></i><b>Phone:</b> 9967120351</p>
                            <p><i class="fas fa-envelope"></i><b>Email:</b> sidjmishra007@student.sfit.ac.in</p>
                            <p><i class="far fa-calendar-alt"></i><b>Date Of Birth:</b> 25-03-2001</p>
                            <p><i class="fas fa-map-marker-alt"></i><b>Address:</b> Mumbai</p>
                            <p><i class="fas fa-code"></i><b>Language:</b> Java, Python, C, C++, Dart</p>
                            <p><i class="fas fa-code"></i><b>Technology:</b> Flutter, Android(Java)</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block script %}
{% endblock %}

my_portfolio_website/my_contact_data/templates/my_contact_data/portfolio.html
  
{% extends 'my_contact_data/base.html' %}
{% load static %}

{% block stylesheets %}
<style>
    body {
        background-color: #E8E8E8;
    }

    .box {
        margin-top: 6rem;

    }

    ul {
        position: relative;
        right: 0;
    }

    .row input {
        margin-bottom: 2rem;
        border: 0;
        box-shadow: 0;
    }

    .row textarea {
        margin-bottom: 2rem;
        border: 0;
    }

    .box h1 {
        margin-bottom: 2rem;
    }

    .icons {
        margin-top: 3rem;
    }

    .copy {
        margin-top: 1rem;
    }

    .icons a {
        color: #ccc;
        margin: 1rem;
    }

    .icons a:hover {
        color: #000;
    }





    * {
        box-sizing: border-box;
    }

    body {
        background-color: #f1f1f1;
        padding: 20px;
        font-family: Arial;
    }

    /* Center website */
    .main {
        max-width: 1000px;
        margin: auto;
    }

    h1 {
        font-size: 50px;
        word-break: break-all;
    }

    .row {
        margin: 8px -16px;
    }

    /* Add padding BETWEEN each column (if you want) */
    .row,
    .row>.column {
        padding: 8px;
    }

    /* Create three equal columns that floats next to each other */
    .column {
        float: left;
        width: 33.33%;
        display: none;
        /* Hide columns by default */
    }

    /* Clear floats after rows */
    .row:after {
        content: "";
        display: table;
        clear: both;
    }

    /* Content */
    .content {
        background-color: white;
        padding: 10px;
    }

    /* The "show" class is added to the filtered elements */
    .show {
        display: block;
    }

    /* Style the buttons */
    .btn {
        border: none;
        outline: none;
        padding: 12px 16px;
        background-color: white;
        cursor: pointer;

    }

    /* Add a grey background color on mouse-over */
    .btn:hover {
        background-color: #ddd;
    }

    /* Add a dark background color to the active button */
    .btn.active {
        background-color: #666;
        color: white;
    }
</style>
{% endblock stylesheets %}


{% block headscript %}
{% endblock headscript %}


{% block content %}


<div class="container">

    <div class="box shadow-lg p-3 mb-5 bg-white rounded">
        <div class="">
            <center>
                <h1 style="color: #15aabf">PORTFOLIO</h1>
            </center>
        </div>



        <div class="container">
            <div class="row">

                <div id="myBtnContainer">

                    <button class="btn active" onclick="filterSelection('all')"> Show all</button>
                    <button class="btn" onclick="filterSelection('nature')"> Nature</button>
                    <button class="btn" onclick="filterSelection('cars')"> Cars</button>
                    <button class="btn" onclick="filterSelection('people')"> People</button>

                </div>


                <!-- Portfolio Gallery Grid -->
                <div class="row">
                    <div class="column nature col-md-4">
                        <div class="content">
                            <img src="{% static 'my_contact_data/images/p1.jpg' %}" alt="Mountains" style="width:100%;height: 200px">

                        </div>
                    </div>
                    <div class="column nature col-md-4">
                        <div class="content">
                            <img src="{% static 'my_contact_data/images/p2.jpg' %}" alt="Lights" style="width:100%;height: 200px">

                        </div>
                    </div>
                    <div class="column nature col-md-4">
                        <div class="content">
                            <img src="{% static 'my_contact_data/images/p3.jpg' %}" alt="Nature" style="width:100%;height: 200px">

                        </div>
                    </div>

                    <div class="column cars col-md-4">
                        <div class="content">
                            <img src="{% static 'my_contact_data/images/p4.jpg' %}" alt="Car" style="width:100%;height: 200px">

                        </div>
                    </div>
                    <div class="column cars col-md-4">
                        <div class="content">
                            <img src="{% static 'my_contact_data/images/p5.png' %}" alt="Car" style="width:100%;height: 200px">

                        </div>
                    </div>
                    <div class="column cars col-md-4">
                        <div class="content">
                            <img src="{% static 'my_contact_data/images/p6.jpg' %}" alt="Car" style="width:100%;height: 200px">

                        </div>
                    </div>

                    <div class="column people col-md-4">
                        <div class="content">
                            <img src="{% static 'my_contact_data/images/p7.png' %}" alt="People" style="width:100%;height: 200px">

                        </div>
                    </div>
                    <div class="column people col-md-4">
                        <div class="content">
                            <img src="{% static 'my_contact_data/images/p8.jpg' %}" alt="People" style="width:100%;height: 200px">

                        </div>
                    </div>
                    <div class="column people col-md-4">
                        <div class="content">
                            <img src="{% static 'my_contact_data/images/p9.jpg' %}" alt="People" style="width:100%;height: 200px">

                        </div>
                    </div>
                </div>


            </div>
        </div>

    </div>
</div>
{% endblock %}

{% block script %}
<script>
    filterSelection("all") // Execute the function and show all columns
    function filterSelection(c) {
        var x, i;
        x = document.getElementsByClassName("column");
        if (c == "all") c = "";
        // Add the "show" class (display:block) to the filtered elements, and remove the "show" class from the elements that are not selected
        for (i = 0; i < x.length; i++) {
            w3RemoveClass(x[i], "show");
            if (x[i].className.indexOf(c) > -1) w3AddClass(x[i], "show");
        }
    }

    // Show filtered elements
    function w3AddClass(element, name) {
        var i, arr1, arr2;
        arr1 = element.className.split(" ");
        arr2 = name.split(" ");
        for (i = 0; i < arr2.length; i++) {
            if (arr1.indexOf(arr2[i]) == -1) {
                element.className += " " + arr2[i];
            }
        }
    }

    // Hide elements that are not selected
    function w3RemoveClass(element, name) {
        var i, arr1, arr2;
        arr1 = element.className.split(" ");
        arr2 = name.split(" ");
        for (i = 0; i < arr2.length; i++) {
            while (arr1.indexOf(arr2[i]) > -1) {
                arr1.splice(arr1.indexOf(arr2[i]), 1);
            }
        }
        element.className = arr1.join(" ");
    }

    // Add active class to the current button (highlight it)
    var btnContainer = document.getElementById("myBtnContainer");
    var btns = btnContainer.getElementsByClassName("btn");
    for (var i = 0; i < btns.length; i++) {
        btns[i].addEventListener("click", function() {
            var current = document.getElementsByClassName("active");
            current[0].className = current[0].className.replace(" active", "");
            this.className += " active";
        });
    }
</script>
{% endblock %}

my_portfolio_website/my_contact_data/templates/my_contact_data/resume.html
{% extends 'my_contact_data/base.html' %}
{% load static %}
{% block stylesheets %}
    {% endblock stylesheets %}

    {% block headscript %}
    {% endblock headscript %}

{% block content %}
<iframe src="{% static 'my_contact_data/Siddhant_resume.pdf' %}" width="100%" height="1000px">
    This browser does not support PDFs. Please download the PDF to view it: Download PDF
    </iframe>

{% endblock %}

{% block script %}
{% endblock %}